{
 "title": "ADQ Cluster Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "node", "query": { "query": "label_values(adq_node_name)" } },
   {
    "name": "namespace",
    "query": {
     "query": "label_values($metric{adq_node_name=~\"$node\"}, adq_pod_namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values($metric{adq_node_name=~\"$node\", adq_pod_namespace=~\"$namespace\"}, adq_pod_name)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values($metric{adq_pod_name=~\"$pod\", adq_pod_namespace=~\"$namespace\"}, adq_container_name)"
    }
   },
   { "name": "metric", "query": { "query": "metrics(adq)" } }
  ]
 },
 "panels": [
  {
   "title": "$metric Count",
   "type": "graph",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "$metric{adq_node_name=~\"$node\", adq_pod_namespace=~\"$namespace\", adq_pod_name=~\"$pod\", adq_container_name=~\"$container\"}",
     "legendFormat": "{{adq_pod_name}}---{{adq_container_name}}---q{{adq_queue_number}}---tc{{adq_tc_number}}"
    }
   ]
  },
  {
   "title": "$metric Instantaneous Rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate($metric{adq_node_name=~\"$node\", adq_pod_namespace=~\"$namespace\", adq_pod_name=~\"$pod\", adq_container_name=~\"$container\"}[30s])",
     "legendFormat": "{{adq_pod_name}}---{{adq_container_name}}---q{{adq_queue_number}}---tc{{adq_tc_number}}"
    }
   ]
  },
  {
   "title": "$metric Rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate($metric{adq_node_name=~\"$node\", adq_pod_namespace=~\"$namespace\", adq_pod_name=~\"$pod\", adq_container_name=~\"$container\"}[30s])",
     "legendFormat": "{{adq_pod_name}}---{{adq_container_name}}---q{{adq_queue_number}}---tc{{adq_tc_number}}"
    }
   ]
  }
 ]
}